id: public-api-performance
displayName: New Relic Public API Performance
description: The Public API Performance dashboard is a dashboard supported by New Relic’s Global Performance data sets. It’s an out-of-the-box dashboard included as part of your New Relic account.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/explore-public-api-performance-dashboard/
icon: logo.svg
