id: 7f8e7ef2-d94b-47bc-8d85-31471430b673
slug: public-api-performance
title: Public API Performance
description: |
  ## Public API Performance

  Explore the performance data New Relic collects about commonly used, public APIs. Use this dashboard to:

    * Determine if a public API you use is experiencing a performance issue
    * Compare the performance of your publicly-available APIs against other services
    * Evaluate the API performance of providers when considering which one(s) to choose
summary: |
  Explore the performance data New Relic collects about commonly used, public APIs. 
level: New Relic
authors:
  - New Relic
keywords:
  - public api
  - performance
  - provider
installPlans:
  - public-api-performance
dataSourceIds:
  - public-api-performance
dashboards:
  - public-api-performance
documentation:
  - name: Public API Performance Dashboard
    url: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/explore-public-api-performance-dashboard/
    description: See our documentation for more details on the Public API Performance Dashboard.
icon: logo.svg
website: https://www.newrelic.com
